name: Deploy to DigitalOcean Staging (Blue/Green)

on:
  workflow_run:
    workflows: ["CI"]
    branches: [dev]
    types:
      - completed
  workflow_dispatch:
    inputs:
      ref:
        description: The ref to check out and deploy (commit sha, tag, branch)
        required: false
        default: dev
        type: string

concurrency:
  group: deployments-staging
  cancel-in-progress: false

permissions:
  contents: read
  actions: read
  packages: read

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Debug print all github.event variables
      shell: bash
      run: echo '${{ toJSON(github.event.workflow_run) }}'

  deploy:
    name: Deploy to Staging
    # if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/_deploy-do.yml
    with:
      environment: staging
      ref: ${{ github.event.workflow_run.head_sha || inputs.ref || 'dev' }}
    secrets: inherit
